### DISCUSSION TITLE
How to change default 6881 port on docker compose

### DISCUSSION THREAD

**Discussion by jmnicolas90** [qbittorrent/docker-qbittorrent-nox#3] [Q&A]
Hi,

I have a problem with a tracker that doesn't accept the default 6881 port (even though I redirected this internal port to another external one, qBittorrent is reporting to the tracker that it uses 6881).

So I changed the default port in the Web UI preferences panel and in the compose file  and restarted the container.

However my torrent client is now refusing incoming connections (it was working with 6881).

I have now this in my compose file :

`ports:`
`      # for bittorrent traffic 6881`
`      - 47189:47189/tcp`
`      - 47189:47189/udp`
`      # for WebUI`
`      - 37429:37429/tcp`

What I need is to tell qBittorrent to change its default port, something like :
`- QBT_WEBUI_PORT=37429`
but for the traffic.

I'd appreciate any help solving this problem, thanks in advance.

**Comment by Chocobo1** [comment]
>What I need is to tell qBittorrent to change its default port, something like :
>- QBT_WEBUI_PORT=37429
>but for the traffic.

You can change it in WebUI at Options -> Connection tab -> Listening Port.

**Comment by jmnicolas90** [comment]
> > What I need is to tell qBittorrent to change its default port, something like :
> > 
> > * QBT_WEBUI_PORT=37429
> >   but for the traffic.
> 
> You can change it in WebUI at Options -> Connection tab -> Listening Port.

This is what I did but qBittorrent is refusing incoming connections.
If I leave the standard 6881 port it allows incoming connections (but then one of my tracker complains).

**Reply by JingleDjango** [reply]
I'm having the same issue. Did you ever resolve this @jmnicolas90 ?

**Reply by newadventure079** [reply]
@jmnicolas90 @JingleDjango Here is my compose file where I successfully change the UI port and the torrenting port

```
version: "3.6"
services:
  qbittorrent-nox-Default:
    container_name: "qbittorrent-nox-Default"
    environment:
      - "PGID=100"
      - "PUID=1026"
      - QBT_LEGAL_NOTICE=confirm
      - QBT_VERSION=latest
      - QBT_WEBUI_PORT=9080
    image: qbittorrentofficial/qbittorrent-nox:latest
    networks:
      - "qbittorrent"
    ports:
      - "6882:6882/tcp"
      - "6882:6882/udp"
      - "9080:9080/tcp"
    restart: "always"
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - /volume2/docker/qbittorrent-nox-Default:/config
      - "/volume1/NAS/Torrents:/downloads"
networks:
  qbittorrent:
    external: true
    name: "qbittorrent"
```
![CleanShot 2025-06-05 at 18 20 25@2x](https://github.com/user-attachments/assets/7ebc5db8-e8a2-4f2a-a3f4-f2af5896b176)



canyouseeme.org shows 6882 as connected.  I'm able to access the WebUI via port 9080.  Everything seems to be fine as far as I know.
