### ISSUE TITLE
Hardcoded /downloads path?

### ISSUE THREAD

**Issue by saberblaze** [qbittorrent/docker-qbittorrent-nox#20]
Using version 4.5.5-1

I migrated from another qBittorrent docker container. Usually torrent docker containers will have a default downloads directory (/downloads in this case) setup in the torrent client settings that needs to be mapped when starting the container. I always change it from the default folder to one that matches the folder name on the host, for example /Media. After transfer the config files from the other container everything works fine except that in the docker logs, the message

`chown: /downloads: No such file or directory`

is always displayed when starting the container, even though that path is not used in client. It doesn't seem to affect the functioning of the client but why is it attempting to run chown in its internal "/downloads" directory?

**Comment by Chocobo1** [comment]
Not sure I fully understand your use case. I would suggest that you set the variable `QBT_DOWNLOADS_PATH` pointing to some folder on the host. And in qbt webUI, keep the default download path (which is `/downloads`). Unless you know what you are doing, don't change `/downloads` to other values or you'll end up with errors.

**Comment by saberblaze** [comment]
Hello, thank you for taking the time. I should have included my docker compose file to better illustrate the question. 

```
version: "3.9"

services:
  qbittorrent:
    image: ghcr.io/qbittorrent/docker-qbittorrent-nox:4.5.5-1
    container_name: qbittorrent
    network_mode: "container:gluetun"
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=000
      - QBT_WEBUI_PORT=6363
      - QBT_EULA=accept
      - QBT_VERSION=4.5.5-1
    volumes:
      - /share/apps/qbittorrent/config:/config
      - /share/Data:/Data
      - /share/Media:/Media
#    ports: exposed through gluetun
#      - 6363:6363
#      - 6881:6881
#      - 6881:6881/udp
    tty: true
    restart: unless-stopped
```

I'm aware that in the default configuration /downloads is mapped to a folder on the host, as is the case with most torrent docker containers. I have the default folder path in the webUI set to /Media but use different categories for subfolders under /Media or for /Data. The reason for opening the issue was to inquire if there was a particular reason why the docker container itself is hardcoded to attempt run "chown" on an internal directory that is not being used or referenced anywhere within the client itself when this is not the case in other containers. I already had the directories and all the torrents set up and configured this way,
since it doesn't affect the functioning of the client I'll leave as is.
