### ISSUE TITLE
Error: unauthorized

### ISSUE THREAD

**Issue by Jannik44** [qbittorrent/docker-qbittorrent-nox#22]
Hello, i just tried to run it behind a reverse proxy but i get an unauthorized error, how to allow access?

**Comment by Chocobo1** [comment]
We have a few wiki pages about setting up reverse proxies that might help you: https://github.com/qbittorrent/qBittorrent/wiki#reverse-proxy-setup-for-webui-access

**Comment by duchenpaul** [comment]
I encountered the same issue, the reason for that is I did not set all ports with the same value, here is how I fixed that:
```yml
version: "3.3"

services:
  qbittorrent-nox:
    image: qbittorrentofficial/qbittorrent-nox:{{ version }}
    container_name: qbittorrent
    environment:
      - QBT_EULA=accept
      - QBT_VERSION=:{{ version }}
      - QBT_WEBUI_PORT={{ http_port }} # <----- here
      - TZ={{ timezone }}
    ports:
      - {{ qbittorrent_tcp_port }}:6881/tcp
      - {{ qbittorrent_tcp_port }}:6881/udp
      - {{ http_port }}:{{ http_port }}/tcp # <----- here, it must be the same as the one defined in QBT_WEBUI_PORT
    volumes:
      - {{ qbittorrent_data_dir }}/config:/config
      - {{ qbittorrent_download_dir }}:/downloads
```
