### ISSUE TITLE
The server does not seem to run in container

### ISSUE THREAD

**Issue by skyhos** [qbittorrent/docker-qbittorrent-nox#52]
Hi, I'm trying `docker-qbittorrent-nox` in my new Rocky Linux 9 server.

my docker-compose:
```
version: "3.7"
networks:
  service_net_1:
    external: true
services:
  mytorrent:
    container_name: mytorrent
    environment:
      - PGID=1000
      - PUID=1000
      - QBT_LEGAL_NOTICE="QBT_LEGAL_NOTICE"
      - BT_VERSION=5.0.1-1
      - QBT_WEBUI_PORT=8080
      - TZ=Asia/Seoul
    image: qbittorrentofficial/qbittorrent-nox:5.0.1-1
    networks:
      service_net_1:
        aliases:
          - mytorrent
    ports:
      #- 80:8080/tcp #Web UI goes to internally to HAProxy
      - 6881:6881/tcp
      - 6881:6881/udp
    volumes:
      - ${CONF_DIR}/hodolrtorrent:/config
      - /mnt/sdb/myTorData:/downloads
    read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
```

And I run the `compose up` and goes into the container.
```
docker exec -it mytorrent /bin/sh
```

And I tried to access via `cURL` to `127.0.0.1` and the results are as follow:
```
/ # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /sbin/tini -g -- /entrypoint.sh
    7 qbtUser   0:00 qbittorrent-nox --profile=/config --webui-port=8080
   21 root      0:00 /bin/sh
   28 root      0:00 ps aux
/ # curl 127.0.0.1:8080
curl: (7) Failed to connect to 127.0.0.1 port 8080 after 0 ms: Could not connect to server
```

I also have the following logs:
```
/config/qBittorrent/data/logs # cat qbittorrent.log
(N) 2024-11-19T23:13:50 - qBittorrent v5.0.2 started. Process ID: 7
(N) 2024-11-19T23:13:50 - Using config directory: /config/qBittorrent/config
(N) 2024-11-19T23:23:20 - qBittorrent v5.0.2 started. Process ID: 8
(N) 2024-11-19T23:23:20 - Using config directory: /config/qBittorrent/config
(N) 2024-11-19T23:29:59 - qBittorrent v5.0.1 started. Process ID: 7
(N) 2024-11-19T23:29:59 - Using config directory: /config/qBittorrent/config
```

Can you please guide me?
