### ISSUE TITLE
File error alert, Permission denied when making a folder

### ISSUE THREAD

**Issue by Sandwich1699975** [qbittorrent/docker-qbittorrent-nox#60]
I get this error for every torrent I try to download

```
File error alert. Torrent: "torrentname". File: "/downloads/torrentname/torrentname.mkv". Reason: "torrentname mkdir (/downloads/torrentname/torrentname.mkv) error: Permission denied"
```

And they all error before downloading any data. 

However, when I `exec -it` into the docker container I can run `mkdir` fine. How do I go about fixing this?

`docker-compose.yml`
```yaml
services:
  qbittorrent-nox:
    # for debugging
    #cap_add:
      #- SYS_PTRACE
    container_name: qbittorrent-nox
    environment:
      #- PAGID=10000
      #- PGID=1000
      #- PUID=1000
      - QBT_LEGAL_NOTICE=${QBT_LEGAL_NOTICE}
      - QBT_VERSION=${QBT_VERSION}
      - QBT_WEBUI_PORT=${QBT_WEBUI_PORT}
      #- TZ=UTC
      #- UMASK=022
    image: qbittorrentofficial/qbittorrent-nox:${QBT_VERSION}
    read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - ${QBT_CONFIG_PATH}:/config
      - ${QBT_DOWNLOADS_PATH}:/downloads
    restart: unless-stopped
    network_mode: host
```

`.env`
```env
# Refer to Readme.md for an explanation of the variables

QBT_LEGAL_NOTICE=confirm
QBT_VERSION=latest
QBT_WEBUI_PORT=8080

QBT_CONFIG_PATH=/home/freddy/.config/qBittorrent
QBT_DOWNLOADS_PATH=/mnt/smb_truenas/Downloads
```

Permissions
```
$ ls -lh /mnt/smb_truenas/
total 0
drwxrwxrwx 2 freddy freddy 0 Feb  3 11:39  Downloads
drwxrwxrwx 2 freddy freddy 0 Feb  3 20:18  Movies
drwxrwxrwx 2 freddy freddy 0 Feb  3 20:19 'TV Shows'
```
