### ISSUE TITLE
Permissions issue - Even after setting GID and GUID, defaulting to root

### ISSUE THREAD

**Issue by PhantomWolf1092** [qbittorrent/docker-qbittorrent-nox#65]
Hello, I am having issues with permissions in my Qbitorrent container.

**Issues**:

1. It doesn't read the free space, therefore giving it "Unknown" error.
2. And also, when I add the torrent it says error on the logs "error: Permission denied"

**Troubleshooting**:

1. I've been trying to isolate the problem, I think it may be because when I run the container with my appid/groupid (1000/1000), it runs it as root anyways?
Even after setting docker-compose.yml GID and GUID as 1000 and removing "read_only" parameter or explicitly tell it false, in any case both still run as root.

```
services:
  qbittorrent-nox:
    # for debugging
    #cap_add:
      #- SYS_PTRACE
    container_name: qbitorrent-nox
    environment:
      #- PAGID=10000
      - PGID=1000
      - PUID=1000
      - QBT_LEGAL_NOTICE=confirm
      - QBT_WEBUI_PORT=8080
      - TZ=UTC
      #- UMASK=022
    image: qbittorrentofficial/qbittorrent-nox:5.0.2-1
    ports:
      -tcp/udp ports
      # for WEBUI
      -8080:8080/tcp
    stop_grace_period: 30m
    volumes:
      - ./config:/config
      - /media/exthdd/downloads:/downloads

```

(Indentation may be wrong here, but I already checked with YAML lint)

```
docker exec -it qbitorrent-nox whoami
root
```

2. My download permissions have not been changed, always 1000/1000 and have 755

3. I already tried latest, [5.0.4-1]. [5.0.3-1], and right now I am on [5.0.2-1].

4. I was able to run a similar container before, but when I experienced admin password problems had to reset it, and here we are.
I can't recall what version I was running before, but about 4 months ago it was just running latest.

5. Reinstalled docker, and added my appid to the docker group as usual

Any ideas?
