### ISSUE TITLE
Host not found for I2P tracker

### ISSUE THREAD

**Issue by zypA13510** [qbittorrent/docker-qbittorrent-nox#66]
## Issue

When I run qbittorrnet-nox using this docker image, i2p trackers show up as "not working" with a message "Host not found (authoritative)". On the i2p router, no SAM bridge is established.
However, when I run regular qbittorrent (GUI) or qbittorrent-nox outside of docker, using the exact same sets of files, they work.

### compose.yaml

```yaml
services:
  qbittorrent-nox:
    environment:
      PGID: 1000
      PUID: 1000
      QBT_LEGAL_NOTICE: confirm
      QBT_WEBUI_PORT: 8080
      UMASK: '002'
    image: qbittorrentofficial/qbittorrent-nox:latest # currently this is 5.0.5-1
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    tmpfs:
      - /tmp
    volumes:
      - ./.config/qBittorrent:/config/qBittorrent/config
      - ./.local/share/qBittorrent:/config/qBittorrent/data
      - ./Downloads:/downloads
```

### qBittorrent.conf

```properties
# only the relevant part is included
[BitTorrent]
Session\I2P\Address=192.168.0.254 # external to docker, I have verified that it's reachable by ping inside the container using docker exec
Session\I2P\Enabled=true
Session\I2P\MixedMode=false # tried both true and false, neither works inside docker
```

## Screenshot

Using docker image:

![Image](https://github.com/user-attachments/assets/94007d81-074f-46d5-8a8c-287f2c4457be)

Using regular qbittorrent-nox outside docker:

![Image](https://github.com/user-attachments/assets/a8da2709-f263-46a9-ba83-b40d37ca9569)

![Image](https://github.com/user-attachments/assets/262f0bdd-abe1-44fe-b46d-b15d8f386f3e)
